apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-inventory
  template:
    metadata:
      labels:
        app: book-inventory
    spec:
      containers:
      - name: inventory
        image: task82c.azurecr.io/inventory:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DATABASE_URL
      - name: book-catalog
        image: task82c.azurecr.io/book-catalog:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 81
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DATABASE_URL