name: Terraform Destroy

on:
  workflow_dispatch:  

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.6'  

    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }} 
    
    - name: Terraform init
      working-directory: ./scripts/terraform
      run: terraform init

    - name: Terraform Destroy:
      working-directory: ./scripts/terraform
      run: terraform destroy

    - name: Refresh terraform
      working-directory: ./scripts/terraform  
      run: terraform refresh