name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Terraform Init
        working-directory: ./scripts/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./scripts/terraform
        run: terraform apply -auto-approve
        continue-on-error: true

      # - name: Get environment variables
      #   working-directory: ./scripts/terraform
      #   run: |
      #     terraform output -raw container_registry_login_server > acr_server.txt
      #     terraform output -raw registry_admin_username > acr_username.txt
      #     terraform output -raw registry_admin_password > arc_password.txt
      #     terraform output -raw kube_config | base64 > kube_config.txt

      #     echo "CONTAINER_REGISTRY=$(cat acr_server.txt)" >> $GITHUB_ENV
      #     echo "REGISTRY_UN=$(cat acr_username.txt)" >> $GITHUB_ENV
      #     echo "REGISTRY_PW=$(cat arc_password.txt)" >> $GITHUB_ENV
      #     echo "KUBE_CONFIG=$(cat kube_config.txt)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt install gh -y
          sudo apt install jq -y

      - name: GitHub-Cli login
        run: |
          echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: Refresh terraform state
        run: terraform refresh

      - name: Set Secrets
        run: |
          acr_name = $(az acr list | jq -r '.[0].loginServer')
          echo "$acr_name"
          gh secret set CONTAINER_REGISTRY --body "$acr_name"
          az acr credential show --name $acr_name" --query "{username:username, passwords:passwords[0].value}" --output json > credentials.json
          gh secret set REGISTRY_UN --body "$(cat credentials.json | jq -r '.username')"
          echo "$(cat credentials.json | jq -r '.username')"
          gh secret set REGISTRY_PW --body "$(cat credentials.json | jq -r '.password')"
          echo "$(cat credentials.json | jq -r '.password')"
          gh secret set KUBE_CONFIG --body "$(terraform output -raw kube_config | base64)"
          echo "$(terraform output -raw kube_config | base64)"
